[versions]
compileSdk = "34"
minSdk = "26"
targetSdk = "34"
versionName = "1.0.0"
versionCode = "1"

gradle-plugin = "8.5.1"
kotlin = "2.0.0"
kotlinx-serialization-json = "1.7.0"
kotlinx-collections-immutable = "0.3.7"
core-ktx = "1.13.1"
ksp = "2.0.0-1.0.22"
ktlint = "12.1.1"
detekt = "1.23.6"
kotlinx-coroutines = "1.8.1"
java-inject = "1"

lifecycle-runtime-ktx = "2.8.3"
activity-compose = "1.9.0"
compose-bom = "2024.06.00"
lifecycle = "2.8.3"
navigation = "2.7.7"
hilt = "2.51.1"
hilt-navigation-compose = "1.2.0"

coil = "2.6.0"
ktor-client = "2.3.11"
orbit = "8.0.0"
material = "1.12.0"
google-services = "4.4.2"
crashlytics = "3.0.2"
firebase = "33.1.2"

junit = "4.13.2"
junit-version = "1.2.1"
espresso-core = "3.6.1"
appcompat = "1.7.0"

compose-destination = "1.10.2"
lottie = "6.5.0"
timber = "5.0.1"
datastore = "1.1.1"

kakao_sdk = "2.12.1"

paging3 = "3.3.2"

cloudy = "0.2.0"

[libraries]
android-build = { module = "com.android.tools.build:gradle", version.ref = "gradle-plugin" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
java-inject = { module = "javax.inject:javax.inject", version.ref = "java-inject" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-compose-destination = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "compose-destination" }
androidx-compose-destination-compiler = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "compose-destination" }

lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

compose-compiler-extension = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-ksp = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor-client" }
ktor-client-engine-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor-client" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor-client"}
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor-client" }
ktor-client-json = { group = "io.ktor", name = "ktor-client-json", version.ref = "ktor-client" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor-client" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor-client" }

orbit-core = { group = "org.orbit-mvi", name = "orbit-core", version.ref = "orbit" }
orbit-viewmodel = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "orbit" }
orbit-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbit" }

datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
crashlytics-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber"}

detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ktlint-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

kakao_sdk = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao_sdk" }

paging3 = { group = "androidx.paging", name = "paging-compose", version.ref = "paging3" }
paging3-domain = { group = "androidx.paging", name = "paging-common", version.ref = "paging3"}

compose-cloudy = { group = "com.github.skydoves", name = "cloudy", version.ref = "cloudy" }

[bundles]
androidx-compose = [
    "androidx-activity-compose",
    "androidx-compose-ui",
    "androidx-compose-lifecycle",
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-runtime",
    "androidx-hilt-navigation-compose",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-compose-material-icons",
    "androidx-compose-destination"
]

ktor-client = [
    "ktor-client-core",
    "ktor-client-engine-cio",
    "ktor-client-content-negotiation",
    "ktor-client-auth",
    "ktor-client-json",
    "ktor-client-logging",
    "ktor-serialization",
]

orbit = ["orbit-core", "orbit-compose", "orbit-viewmodel"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }

# Gradle Plugin
wespot-android-application = { id = "com.bff.wespot.application", version = "unspecified" }
wespot-android-library = { id = "com.bff.wespot.android.library", version = "unspecified" }
wespot-android-feature = { id = "com.bff.wespot.feature", version = "unspecified" }
wespot-android-firebase = { id = "com.bff.wespot.firebase", version = "unspecified" }
wespot-android-compose = { id = "com.bff.wespot.compose", version = "unspecified" }
wespot-android-hilt = { id = "com.bff.wespot.hilt", version = "unspecified" }
wespot-android-ktlint = { id = "com.bff.wespot.ktlint", version = "unspecified" }
wespot-jvm-library = { id = "com.bff.wespot.jvm.library", version = "unspecified" }
